# Configurations for locpat package
# Pattern format configuration:
# The shortest path from any given atom in the pattern to the central bond
# can at most contain *max_tbond_level* tbond
max_tbond_level: 1
# The shortest path from any given atom in the pattern to the central bond
# can at most contain *max_hbond_level* hbond, excluding the central bond.
max_hbond_level: 0

# column numbers are 0-based
# hbond column id's
hbond:
  donor_col: 12
  accpt_col: 13
  res_cols:
    - 4
    - 5
    - 6
    - 7
  rot_cols:
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
  flags_col: 21

# tbond column id's
tbond:
  left_col: 6
  right_col: 7
  flags_col: 15
  vdw_col: 21
  rot_phi: 13
  rot_cols:
    - 10
    - 11
    - 12
  res_col: 2