# Configurations for locpat package
# Pattern format configuration:
# The shortest path from any given atom in the pattern to the central bond
# can at most contain *max_tbond_level* tbond
# Set to -1 to ignore tbonds. (0 will include internal tbonds)
max_tbond_level: 1
# The shortest path from any given atom in the pattern to the central bond
# can at most contain *max_hbond_level* hbond, including the central bond.
max_hbond_level: 0

# column numbers are 0-based
# hbond column id's
hbond:
  donor_col: 12
  accpt_col: 13
  res_cols:
    - 4
    - 5
    - 6
    - 7
  rot_phi: 18
  rot_cols:
    - 15
    - 16
    - 17
  flags_col: 21

# tbond column id's
tbond:
  left_col: 6
  right_col: 7
  flags_col: 15
  vdw_col: 21
  rot_phi: 13
  rot_cols:
    - 10
    - 11
    - 12
  res_col: 2

max_step: 791  # max step number to include in analysis
min_for_cluster: 30  # min freq for clustering analysis

abacus: False  # Run this on abacus cluster. Prepends all paths with $WORK.
protdir: cdp/prot
optsdir: cdp/opts
tertdir: cdp/tertiary
outdir: cdp
cpu_per_node: 24